export const GENERATED_QUESTION_SUGGESTION_TIER_SIZE = 1;
export const GENERATED_QUESTION_SUGGESTION_COUNT = GENERATED_QUESTION_SUGGESTION_TIER_SIZE * 3;
export const GENERATED_QUESTION_TIER_LABELS = ["Easy", "Medium", "Hard"] as const;
export const GENERATED_QUESTION_COUNT = GENERATED_QUESTION_TIER_LABELS.length;
export const RAW_GENERATED_QUESTION_COUNT = GENERATED_QUESTION_COUNT;
